### ISSUE TITLE
Karura failed to decode block 43244 and 43249

### ISSUE THREAD

**Issue by jiqiang90** [AcalaNetwork/acala-types.js#59]
Hi team, after updated to polkadotjs 11, we had issue decode with these two blocks in Karura.
 
![image](https://github.com/AcalaNetwork/acala-types.js/assets/10431657/1f63b49c-0af5-455f-8284-b80f729c9ee7)

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura.api.onfinality.io%2Fpublic-ws#/explorer/query/43244

I found those types are missing, but I'm not 100% sure with runtime versions. Could you please check and make an update? Thank you
```
      DispatchTime: {
          _enum: {
              At: 'BlockNumber',
              After: 'BlockNumber'
          }
      },
      CallOf: 'Call',
      AsOriginId: 'AuthoritysOriginId',
      AuthoritysOriginId: {
          _enum: [
              'Root',
              'EaveTreasury',
              'CdpTreasury',
              'ElpTreasury',
              'DSWF'
          ]
      },
      DispatchErrorModule: 'DispatchErrorModuleU8'


```

**Comment by shunjizhan** [comment]
fixed by #60
